### ISSUE TITLE
Error when using functions from class "Region"

### ISSUE THREAD

**Issue by oggethealmighty** [RomeoDespres/reapy#101]
Hi! I have a very small and simple code that should extract the region start time of the indexed region. It looks like this:

`import reapy`
`import reapy.reascript_api as rpr`

`project = reapy.Project()`
`Project = reapy.core.Project(None, -1)`
`Region = reapy.core.Region(project)`

`test_region = Project.regions[0]`
`print(test_region.start)`

However, when I run this code I get this error:

Exception has occurred: DistError

An error occurred while running a function inside REAPER. Traceback was :

Traceback (most recent call last):
  File "C:\Users\oskar.hansson\AppData\Local\Programs\Python\Python38\lib\site-packages\reapy\tools\network\server.py", line 67, in _process_request
    result["value"] = request["function"](*args, **kwargs)
  File "C:\Users\oskar.hansson\AppData\Local\Programs\Python\Python38\lib\site-packages\reapy\core\project\region.py", line 167, in start
    args = self.project_id, self._get_enum_index(), 0, 0, 0, 0, 0
  File "C:\Users\oskar.hansson\AppData\Local\Programs\Python\Python38\lib\site-packages\reapy\core\project\region.py", line 28, in _get_enum_index
    return next(
  File "C:\Users\oskar.hansson\AppData\Local\Programs\Python\Python38\lib\site-packages\reapy\core\project\region.py", line 30, in <genexpr>
    if r.index == region.index
NameError: name 'region' is not defined
  File "C:\Users\oskar.hansson\AppData\Roaming\REAPER\Scripts\CustomScripts\RegionExpander.py", line 12, in <module>
    print(test_region.start)

I tried changing `region.index` in the reapy\core\project\region.py file to `self.index` and I even tried going around the whole `_get_enum_index()` function but I always get the same error. Is there something I'm doing wrong or is there something weird going on with the API?

**Comment by RomeoDespres** [comment]
Hi, looks like a typo in the reapy code... Sorry about that and thank you for spotting it. I'll fix it soon and let you know when an update has been pushed.

**Comment by Levitanus** [comment]
I've made huge fix of markers and regions. It should be in the #92 
Please, take a look on my PRs
Only #85 is not ready to push

**Comment by Levitanus** [comment]
I really, really want to finish my job on the #85, but absolutely have no time. It's my dream to have a spare month for the **reapy**...

**Comment by RomeoDespres** [comment]
Thanks @Levitanus, I'll check this out then!

**Comment by RomeoDespres** [comment]
Hi, this bug should be fixed in version 0.9.0. Please upgrade reapy and let me know if anything goes wrong.Thanks again @teetow and @Levitanus for your help in solving this!
