### ISSUE TITLE
Error when setting up reapy.

### ISSUE THREAD

**Issue by carrus2049** [RomeoDespres/reapy#120]
Greetings. Sorry for the noob question tho I tried to setup reapy by running

`python -c "import reapy; reapy.configure_reaper()"`

and get following error and REAPER just quit.

```Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\reapy\tools\network\web_interface.py", line 25, in get_reapy_server_port
    port = self.ext_state["server_port"]
  File "D:\Anaconda3\lib\site-packages\reapy\tools\network\web_interface.py", line 48, in __getitem__
    raise UndefinedExtStateError(key)
reapy.errors.UndefinedExtStateError: ('Undefined extended state for key server_port.', 'server_port')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\reapy\__init__.py", line 25, in <module>
    from .tools import (
  File "D:\Anaconda3\lib\site-packages\reapy\tools\__init__.py", line 4, in <module>
    from ._inside_reaper import inside_reaper, dist_api_is_enabled
  File "D:\Anaconda3\lib\site-packages\reapy\tools\_inside_reaper.py", line 8, in <module>
    from .network import machines
  File "D:\Anaconda3\lib\site-packages\reapy\tools\network\machines.py", line 139, in <module>
    connect("localhost")
  File "D:\Anaconda3\lib\site-packages\reapy\tools\network\machines.py", line 92, in __init__
    register_machine(host)
  File "D:\Anaconda3\lib\site-packages\reapy\tools\network\machines.py", line 135, in register_machine
    CLIENTS[host] = client.Client(interface.get_reapy_server_port(), host)
  File "D:\Anaconda3\lib\site-packages\reapy\tools\network\web_interface.py", line 29, in get_reapy_server_port
    self.activate_reapy_server()
  File "D:\Anaconda3\lib\site-packages\reapy\tools\network\web_interface.py", line 19, in activate_reapy_server
    self.perform_action(action_name)
  File "D:\Anaconda3\lib\site-packages\reapy\tools\network\web_interface.py", line 35, in perform_action
    request.urlopen(url)
  File "D:\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\Anaconda3\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "D:\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Anaconda3\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "D:\Anaconda3\lib\urllib\request.py", line 1320, in do_open
    r = h.getresponse()
  File "D:\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "D:\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "D:\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

by `import reapy` alone got 
```
D:\Anaconda3\lib\site-packages\reapy\tools\network\machines.py:99: DisabledDistAPIWarning: Can't reach distant API. Please start REAPER, or call reapy.config.enable_dist_api() from inside REAPER to enable distant API.
  warnings.warn(errors.DisabledDistAPIWarning())
```

Been working around it for a few days and haven't got a solution. Plz take a look on it, thanks!

**Comment by carrus2049** [comment]
Also tried on MacOS and the got similar error.
```
Traceback (most recent call last):
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/network/web_interface.py", line 25, in get_reapy_server_port
    port = self.ext_state["server_port"]
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/network/web_interface.py", line 48, in __getitem__
    raise UndefinedExtStateError(key)
reapy.errors.UndefinedExtStateError: ('Undefined extended state for key server_port.', 'server_port')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/__init__.py", line 25, in <module>
    from .tools import (
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/__init__.py", line 4, in <module>
    from ._inside_reaper import inside_reaper, dist_api_is_enabled
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/_inside_reaper.py", line 8, in <module>
    from .network import machines
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/network/machines.py", line 139, in <module>
    connect("localhost")
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/network/machines.py", line 92, in __init__
    register_machine(host)
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/network/machines.py", line 135, in register_machine
    CLIENTS[host] = client.Client(interface.get_reapy_server_port(), host)
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/network/web_interface.py", line 29, in get_reapy_server_port
    self.activate_reapy_server()
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/network/web_interface.py", line 19, in activate_reapy_server
    self.perform_action(action_name)
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/site-packages/reapy/tools/network/web_interface.py", line 35, in perform_action
    request.urlopen(url)
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Users/Carrus/opt/anaconda3/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by carrus2049** [comment]
Been taking hints from #103 and checking everything. Turns out its the proxy setting messing up the connection between reapy and REAPER. It's fixed and ready to go!

Thanks for the great library mate, I'm trying to manipulate REAPER from python script for some rather huge data processing task, basically create, import audio and rendering by track group. I'll see how it's going and definitely happy to contribute!

**Comment by RomeoDespres** [comment]
Happy to hear you managed to make it work, and thanks for the nice comments! Good luck with your project!
