### ISSUE TITLE
Script Execution Error - Windows - ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by colin-vandervort** [RomeoDespres/reapy#132]
I'm trying to set up Reapy on a second windows machine right now, but I can't get it to import properly. It keeps throwing an error noting that the _ctypes module failed to import.

I've tried several reinstalls of python (3.11.1) and tried adding my Python DLL directory to my paths list. Curious if anyone has any other angles I should try. Here's the full error:

Script execution error

Traceback (most recent call last):
  File "C:\/Program Files//REAPER (x64)//Plugins\reaper_python.py", line 2, in <module>
    from ctypes import *
  File "C:\Program Files\Python311\Lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

**Comment by Levitanus** [comment]
I found it very strange and, probably, not related to the package...
If I have time Sunday, maybe I'll try to reproduce the bug. But... probably, something is wrong with a Python.

Actually, there is a problem with a build dependency of `utils`, but I don't see any connections to the Python std package of ctypes...
