### ISSUE TITLE
Cannot add MIDI note in item/take

### ISSUE THREAD

**Issue by kostikvento** [RomeoDespres/reapy#24]
When adding MIDI notes to item (actually to item's take) nothing happens. Here's what I did in shell:

```
>>> import reapy
>>> p = reapy.Project()
>>> t = p.add_track()
>>> mi = t.add_midi_item(0, 10)
>>> tk = mi.active_take
>>> tk.add_note(0, 2, 60)
```

Item appears in Reaper, yet no notes seen. Neither in MIDI editor.

**Comment by kostikvento** [comment]
Exploring things shows that active take is actually undefined, and the item contains no takes at all. Adding takes makes no effect.

```
>>> tk
Take("(MediaItem_Take*)0x0000000000000000")
>>> mi.takes
[]
>>> mi.n_takes
0
>>> mi.add_take()
Take("(MediaItem_Take*)0x0000000000000000")
>>> mi.takes
[]
>>> mi.n_takes
0
```

The reason is that MIDI item's id is rather strange:

```
>>> mi
Item(['(MediaItem*)0x00007FC7A5F3DBC0', '(MediaTrack*)0x00007FC7A6D87000', 0, 10, 0])
>>> mi.id
['(MediaItem*)0x00007FC7A5F3DBC0', '(MediaTrack*)0x00007FC7A6D87000', 0, 10, 0]
>>> it = t.add_item(20, 30)
>>> it
Item("(MediaItem*)0x00007FC7A852C510")
>>> it.id
'(MediaItem*)0x00007FC7A852C510'
```

And the reason is that `Track.add_midi_item` has a typo which wraps item with a wrong id:
```item_id = RPR.CreateNewMIDIItemInProj(self.id, start, end, quantize)```
which should be
```item_id = RPR.CreateNewMIDIItemInProj(self.id, start, end, quantize)[0]```

**Comment by kostikvento** [comment]
After fix in pull request it's okay to add note with `unit="seconds"`:

```>>> tk.add_note(0, 2, 60)```

but `unit="beats"` throws an exception:
```
>>> tk.add_note(4, 6, 64, unit='beats')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/khlyzov/projects/reapy/reapy/core/item/take.py", line 117, in add_note
    Program(code).run(take=self, unit=unit, args=args)
  File "/Users/khlyzov/projects/reapy/reapy/tools/dist_program.py", line 33, in run
    return CLIENT.run_program(self, input)
  File "/Users/khlyzov/projects/reapy/reapy/reascript_api/network/client.py", line 51, in run_program
    raise DistError(result["traceback"])
reapy.errors.DistError: 
An error occurred while running a Program in REAPER. Traceback was :
Traceback (most recent call last):
  File "/Users/khlyzov/projects/reapy/reapy/reascript_api/network/server.py", line 71, in _process_request
    result["value"] = program.run(**request["input"])
  File "/Users/khlyzov/projects/reapy/reapy/tools/program.py", line 86, in run
    exec(self._code, input)
  File "<string>", line 2, in <module>
  File "/Users/khlyzov/projects/reapy/reapy/core/track/track.py", line 82, in _get_project
    project, = Program(code, "project").run(track=self)
  File "/Users/khlyzov/projects/reapy/reapy/tools/program.py", line 86, in run
    exec(self._code, input)
  File "<string>", line 1, in <module>
AttributeError: module 'reapy' has no attribute 'projects'
```
