### ISSUE TITLE
Broken pipe when program completes

### ISSUE THREAD

**Issue by ryerson** [RomeoDespres/reapy#33]
Every time a script with a `reapy` client exits, the server raises the following exception:

```
Deferred script execution error

Traceback (most recent call last):
  File "defer", line 1, in <module>
  File "activate_reapy_server.py", line 27, in main_loop
    SERVER.send_results(results)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/reapy/reascript_api/network/server.py", line 115, in send_results
    self._send_result(connection, result)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/reapy/reascript_api/network/server.py", line 82, in _send_result
    connection.send(result)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/reapy/reascript_api/network/socket.py", line 68, in send
    self._socket.sendall(length)
BrokenPipeError: [Errno 32] Broken pipe
```
The user is required to manually close the error pop-up through the GUI. Is there any for the client to close the connection, so that this doesn't happen every time a program completes execution?

System info:
OSX 10.14.6
python 3.7.4
python-reapy 0.3.0
Reaper v5.983

**Comment by kostikvento** [comment]
This was fixed in pull request https://github.com/RomeoDespres/reapy/pull/28 and is still waiting for a new release.

**Comment by RomeoDespres** [comment]
Uups sorry, been lazy about the releases... I'll fix that asap and let you know!

**Comment by ryerson** [comment]
Thank you!

**Comment by RomeoDespres** [comment]
Done! A lot of internal changes in this new release so I hope everything works for you... Please let me know if it's not the case!

**Comment by ryerson** [comment]
Works like a charm, thank you :)
