### ISSUE TITLE
potential sockets leakage

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#45]
in [my package](https://github.com/Levitanus/session-management) i'm implementing folowing structure:
![connections](https://user-images.githubusercontent.com/29713891/70642333-9b439080-1c71-11ea-9074-3d06ee88934c.png)
While I had server only on slave.py everything was OK, but adding server at master.py made things weird:
Occasionally, I cannot make it stable, catching some crashes, within separatelly turning master and slave scripts on and off when both: master.py and slave.py has servers.
Because of non-verbose Reaper crashes I cannot find the point of failure, but sometimes I catch traceback to the reapy.defer and distant_api. Can it be some tcp conflicts of my servers and reapy?

https://www.youtube.com/watch?v=vF0wT0BA8xI&feature=youtu.be
(the last reaper dissapearing is crash)

**Comment by Levitanus** [comment]
server code:

```Python
class ServerThread(Thread):
    """Thread, supposing to run socketserver.

    Example:
        handlers = [PrintHandler, PingHandler]
        s_server = ReaperServer(handlers, main, host_port=(HOST, PORT))
        rpr.at_exit(s_server.stop)
        s_server.start()
    """
    def __init__(self, server: ss.ThreadingTCPServer) -> None:
        super().__init__(daemon=True)
        self.server = server

    def run(self) -> None:
        """Start server daemon."""
        self.server.serve_forever()


class ReaperServer:
    at_exit: ty.Optional[ty.Callable[[], None]]

    def __init__(
        self,
        handlers: ty.List[ty.Type[IHandler]],
        event_loop: ty.Callable[[], None],
        host_port: ty.Tuple[str, int] = (DEF_HOST, DEF_PORT),
        at_exit: ty.Optional[ty.Callable[[], None]] = None
    ) -> None:
        log('initializing server:')
        self.host, self.port = host_port
        self.handler = SlaveTCPHandler
        for handler in handlers:
            self.handler.register(handler())
        self.event_loop = event_loop
        self.at_exit = at_exit
        rpr.at_exit(self.stop)
        log('creating a TCP server')
        self.server = ss.ThreadingTCPServer(
            (self.host, self.port),
            SlaveTCPHandler,
            bind_and_activate=False,
        )
        self.server.allow_reuse_address = True

        log('creating a TCP server thread')
        self.server_thread = ServerThread(self.server)

    def start(self) -> None:
        """Start TCP server and run event loop."""
        log('starting TCP server')
        self.server.server_bind()
        self.server.server_activate()
        self.server_thread.start()
        log('running event loop')
        self._run()

    def stop(self) -> None:
        """Stop server and cleanup."""
        log('closing everything')
        self._cleanup()
        log('done')

    def _run(self) -> None:
        self.event_loop()
        rpr.defer(self._run)

    def _cleanup(self) -> None:
        if self.at_exit is not None:
            log('perform at_exit')
            self.at_exit()
        self.server.shutdown()
        self.server.server_close()
        self.server_thread.join()
```

**Comment by Levitanus** [comment]
P.S. catched exeption:
(run slave, pass some ping packages, stop it, then run again -> exception)
```
Traceback (most recent call last):
  File "defer", line 1, in <module>
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/core/reaper/defer.py", line 48, in run
    callback(*args, **kwargs)
  File "activate_reapy_server.py", line 20, in run_main_loop
    SERVER.accept()
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/socket.py", line 21, in g
    return f(*args, **kwargs)
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/server.py", line 77, in accept
    connection, address = super().accept()
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/socket.py", line 27, in accept
    connection, address = self._socket.accept(*args, **kwargs)
  File "/usr/lib/python3.7/socket.py", line 212, in accept
    fd, addr = self._accept()
socket.timeout: timed out
```

**Comment by RomeoDespres** [comment]
Hi, thanks for all this material, I'll take a look at it this weekend!

**Comment by Levitanus** [comment]
OK, i finished tonight within several conclusions:

* reaper just hates daemonic threads.
* actually it really don't like python threads, and handles them properly only at one script at time
* anything done inside child thread is better to bring to defer

finally working server example (running version will be awailble im my repo):
```Python
class ReaperServer:
    def __init__(
        self, host: str, port: int, handlers: ty.List[ty.Type[IHandler]]
    ) -> None:
        for handler in handlers:
            SlaveTCPHandler.register(handler())
        self._server = ss.TCPServer(
            (host, port), SlaveTCPHandler, bind_and_activate=False
        )
        self._server.timeout = .02
        self._server.allow_reuse_address = True
        self._server.server_bind()
        self._server.server_activate()

    def run(self) -> None:
        Thread(target=self._server.handle_request).start()

    def at_exit(self) -> None:
        log('closing master')
        log('active threads:')
        for tr in tr_enum():
            if tr is main_thread():
                continue
            log(f'    {tr}')
        for tr in tr_enum():
            if tr is main_thread():
                continue
            log(f'joining {tr} thread')
            tr.join(.1)
            if tr.is_alive():
                log('timeout')
        log('closing server')
        self._server.server_close()
        log('master closed')

handlers = [PrintHandler, PingHandler]
server = ReaperServer(HOST, PORT, handlers)


def main_loop() -> None:
    server.run()
    if rpr.is_inside_reaper():
        rpr.defer(main_loop)
    else:
        main_loop()


def at_exit() -> None:
    server.at_exit()


print('starting slave')
rpr.at_exit(at_exit)
main_loop()
```

P.S. Still, I rarely get timeout error caused by reapy, but it, at least does nothing except showing dialog box) Thanks for awesome tool!

**Comment by RomeoDespres** [comment]
I'm not that surprised that REAPER has trouble with python threads even though I have no idea why. So your problem is basically solved right? Except for this timeout error, but it may be a different issue. I would be interested though if you could provide a sample code to reproduce this bug, cause I find it quite surprising.

**Comment by Levitanus** [comment]
> I would be interested though if you could provide a sample code to reproduce this bug, cause I find it quite surprising.

Well, I really can't find strict connection for making representative step-by-step instruction. When I have enough cases - I will provide example. Let this issue be opened for a while, I feel there is something in reapy sockets mechanic to be, at least, documented for the future generations :)

**Comment by Levitanus** [comment]
OK, I found something:
In case of connecting to localhost with disabled Reaper web interface, import and connect() raises the DistAPIError

But, in case of connecting to the slave machine — not, because of using `socket._GLOBAL_DEFAULT_TIMEOUT` inside of urllib.
My hotfix of `reapy.web_interface.ExtState` works, as I see, but I can't imagine the consequences of such timeout seting.
```Python
class ExtState:
    def __init__(self, web_interface):
        self._url = web_interface._url + "{method}/EXTSTATE/reapy/{key}"

    def __getitem__(self, key):
        url = self._url.format(method="GET", key=key)
        string = request.urlopen(url, timeout=.5).read().decode("utf-8")
        value = string.split("\t")[-1][:-1]
        if not value:
            raise UndefinedExtStateError(key)
        value = json.loads(value)
        return value
```

Also, I don't think, that connect should throw warning on fail, It's quite a trick to catch a warning, but much more verbose to fail on exception.
