### ISSUE TITLE
update play_state dict

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#47]
Script execution error
```
Traceback (most recent call last):
  File "master.py", line 43, in <module>
    main_loop()
  File "master.py", line 27, in main_loop
    if rpr.Project().play_state() not in ('play, record'):
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/core/project/project.py", line 688, in play_state
    state = states[RPR.GetPlayStateEx(self.id)]
KeyError: 0
```

worked:

```Python
    @property
    def play_state(self):
        """
        Project play state ("play", "pause" or "record").

        :type: str
        """
        states = {0: 'stop', 1: "play", 2: "pause", 4: "record"}
        state = states[RPR.GetPlayStateEx(self.id)]
        return state
```

**Comment by RomeoDespres** [comment]
Thanks! This issue has already been spotted on the REAPER forums. The latest version on `pip` (and the master branch) have it fixed. `play_state` has been removed and replaced by more explicit properties, see details [here](https://github.com/RomeoDespres/reapy/blob/master/CHANGELOG.md#050---2019-11-23).
