### ISSUE TITLE
add 'outside_reaper' mode for defer and at_exit

### ISSUE THREAD

**Issue by Levitanus** [RomeoDespres/reapy#48]
I think it's good idea to make this functions availble to run outside for just testing purposes.
I've built this implementation in 10 minutes, maybe there is a point to test it and include?

```Python
import reapy as rpr
import atexit
import time


def safe_defer(f, *args, **kwargs):
    if rpr.is_inside_reaper():
        return rpr.defer(f, *args, **kwargs)
    time.sleep(.03)
    return f(*args, **kwargs)


def safe_at_exit(f, *args, **kwargs):
    if rpr.is_inside_reaper():
        return rpr.at_exit(f, *args, **kwargs)
    atexit.register(f, *args, **kwargs)


if __name__ == '__main__':

    def test_loop(i):
        print(i)
        safe_defer(test_loop, i + 1)

    safe_at_exit(print, 'exiting')
    test_loop(0)
```
P.S. I'll wrap original functions in my local copy of reapy and watch how things will go.
I don't like this sleep(.03) statement, because, as I interpret ReaScript explanation, defer is more like acync call, then just waiting. So, theoretically something like that:

```Python
defer(first)
defer(second)
defer(third)
```

will be put in queue, but executed shorter than in .09 sec

**Comment by Levitanus** [comment]
well, generally it works, but, again, until I run my servers which are now not causing errors in "inside_reaper" mode. (#45 )

```
starting server at 127.0.0.1:49542
starting master
Traceback (most recent call last):
  File "/home/levitanus/gits/session-management/session_management/master.py", line 40, in <module>
    main_loop()
  File "/home/levitanus/gits/session-management/session_management/master.py", line 30, in main_loop
    rpr.defer(main_loop)
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/core/reaper/defer.py", line 160, in defer
    return f(*args, **kwargs)
  File "/home/levitanus/gits/session-management/session_management/master.py", line 30, in main_loop
    rpr.defer(main_loop)
 ...
    return f(*args, **kwargs)
  File "/home/levitanus/gits/session-management/session_management/master.py", line 27, in main_loop
    if is_stopped():
  File "/home/levitanus/gits/session-management/session_management/common.py", line 66, in is_stopped
    return rpr.Project().play_state not in ('play, record')
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/core/project/project.py", line 24, in __init__
    id = RPR.EnumProjects(index, None, 0)[0]
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/inside_reaper_.py", line 66, in wrap
    return _CLIENT.request(f, {"args": args, "kwargs": kwargs})
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/client.py", line 23, in request
    result = self._get_result()
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/client.py", line 16, in _get_result
    s = self.recv(timeout=None).decode()
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/socket.py", line 53, in recv
    return self._socket.recv(length, socket.MSG_WAITALL)
MemoryError
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/levitanus/gits/session-management/session_management/networking.py", line 253, in _listen
    data[len(ANNOUNCE_STRING):]
  File "/home/levitanus/gits/session-management/session_management/common.py", line 23, in __call__
    rpr.print(line)
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/core/reaper/reaper.py", line 402, in print
    show_console_message(*args, **kwargs)
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/core/reaper/reaper.py", line 558, in show_console_message
    RPR.ShowConsoleMsg(txt)
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/inside_reaper_.py", line 66, in wrap
    return _CLIENT.request(f, {"args": args, "kwargs": kwargs})
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/client.py", line 23, in request
    result = self._get_result()
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/client.py", line 17, in _get_result
    return json.loads(s)
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/json.py", line 42, in loads
    return json.loads(s, object_hook=object_hook)
  File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/levitanus/gits/session-management/session_management/master.py", line 34, in at_exit
    gui_server.at_exit()
  File "/home/levitanus/gits/session-management/session_management/networking.py", line 182, in at_exit
    log('closing master')
  File "/home/levitanus/gits/session-management/session_management/common.py", line 23, in __call__
    rpr.print(line)
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/core/reaper/reaper.py", line 402, in print
    show_console_message(*args, **kwargs)
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/core/reaper/reaper.py", line 558, in show_console_message
    RPR.ShowConsoleMsg(txt)
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/inside_reaper_.py", line 66, in wrap
    return _CLIENT.request(f, {"args": args, "kwargs": kwargs})
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/client.py", line 23, in request
    result = self._get_result()
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/client.py", line 16, in _get_result
    s = self.recv(timeout=None).decode()
  File "/home/levitanus/.local/lib/python3.7/site-packages/reapy/tools/network/socket.py", line 53, in recv
    return self._socket.recv(length, socket.MSG_WAITALL)
MemoryError
[Finished in 2.5s with exit code 1]
[shell_cmd: "/usr/bin/python3" -u "/home/levitanus/gits/session-management/session_management/master.py"]
[dir: /home/levitanus/gits/session-management/session_management]
[path: /home/levitanus/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin]
```

I need time to unbound this)

**Comment by RomeoDespres** [comment]
I'm not sure about this one... Deferring execution outside REAPER does not mean anything without context. I feel implementing some outside REAPER behavior for `defer` makes its purpose unclear (especially for newcomers that easily get confused with the deferring mechanism). I mean, if you define the purpose of `defer`, it would be (as you said): *queue up execution of the function to let the main thread continue with the GUI loop*. But there is no GUI loop when running Python outside REAPER. Or, if there is one, it is defined by the user, who should have the freedom to decide whether the deferred function will run in .03 seconds, or in another thread, or not at all, etc. If you have code that uses `defer` and must run inside *and* outside REAPER, then I think it is better if you explicitly code your own logic, using e.g. `if reapy.is_inside_reaper()` conditions.

**Comment by Levitanus** [comment]
OK let's close on this conclusion :)
